services:
  node-app:
    build:
      context: .
    container_name: portfolio-react
    environment:
      - CHOKIDAR_USEPOLLING=true
      - SERVER_PORT=3000
    volumes:
      - ./:/app
      - /app/node_modules
    expose:
      - 3000
    ports:
      - 3000:3000
    stdin_open: true
    tty: true